#!/bin/sh

#
# Copyright (c) 2011 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

# Must be at the beginning
. /usr/share/debconf/confmodule

update-rc.d -f neubot remove

if [ "$1"x = "purge"x ]; then
	rm -rf /var/neubot
fi

#
# XXX Unconditionally purge the database so when we upgrade
# the new version can reask the user for permission if
# needed.
# I need to do that because Ubuntu Software Center does
# not seem to honour the `db_fset` command and so the
# preinst script does not work as it should.
# This problem has been noted with Ubuntu Software Center
# only, while dpkg and gdebi seem to work fine.
#
db_purge
