#!/bin/sh -e

#
# Copyright (c) 2011 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

# Must be at the beginning
. /usr/share/debconf/confmodule

if [ -f /var/neubot/database.sqlite3 ]; then

    INFORMED=$(sqlite3 /var/neubot/database.sqlite3 \
        'SELECT value FROM config WHERE name="privacy.informed";')
    CAN_COLLECT=$(sqlite3 /var/neubot/database.sqlite3 \
        'SELECT value FROM config WHERE name="privacy.can_collect";')

    # Backward compat
    if [ "$INFORMED" = "true" ]; then
        INFORMED=1
    fi
    if [ "$CAN_COLLECT" = "true" ]; then
        CAN_COLLECT=1
    fi

    if [ "$INFORMED" = "1" -a "$CAN_COLLECT" = "1" ]; then
        exit 0
    fi
fi

#
# The user cannot tell debconf to filter out critical
# questions.  We are sure the user will take a decision
# with respect to her IP address treatment.  Unless
# she choses the noninteractive setup.
#
db_fset neubot/privacy seen false
db_input critical neubot/privacy || true
db_go

#
# Create the database, honour user response
# and actually update settings.
#
install -d /var/neubot
sqlite3 /var/neubot/database.sqlite3 'CREATE TABLE IF NOT EXISTS config(name TEXT PRIMARY KEY, value TEXT);'

db_get neubot/privacy
if [ "$RET" = "collect only" ]; then
    INFORMED=1
    CAN_COLLECT=1
    CAN_SHARE=0
elif [ "$RET" = "collect and share" ]; then
    INFORMED=1
    CAN_COLLECT=1
    CAN_SHARE=1
else
    INFORMED=0
    CAN_COLLECT=0
    CAN_SHARE=0
fi

sqlite3 /var/neubot/database.sqlite3 "INSERT OR REPLACE INTO config(name, value) VALUES('privacy.informed', $INFORMED);"
sqlite3 /var/neubot/database.sqlite3 "INSERT OR REPLACE INTO config(name, value) VALUES('privacy.can_collect', $CAN_COLLECT);"
sqlite3 /var/neubot/database.sqlite3 "INSERT OR REPLACE INTO config(name, value) VALUES('privacy.can_share', $CAN_SHARE);"
